version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: healthi_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthi_marketplace
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount the sql file so we can run it easily
      - ./database:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
